### ISSUE TITLE
What set of versions of `mmcv` or `mmcv-full` and other related packages can work with cuda?

### ISSUE THREAD

**Issue by JoyLinWQ** [xavibou/ovdsat#1]
Hi @xavibou , thanks for releasing the wonderful code for this.

I'm curious what versions of mmcv or mmcv-full packages you have used that works when running the training for `bash scripts/train_prototypes_bbox.sh`.

I'm following all the mmcv-related import fixes here - https://github.com/OpenGVLab/InternImage/issues/91.
and stuck at current import fix - unable to find any resources:

```
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\mmcv\device\ipu\__init__.py", line 3, in <module>
    from mmcv.utils.device_type import IS_IPU_AVAILABLE
ImportError: cannot import name 'IS_IPU_AVAILABLE' from 'mmcv.utils.device_type'
```
while trying to fix

```
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\mmcv\device\ipu\__init__.py", line 3, in <module>
    from mmcv.utils import IS_IPU_AVAILABLE
ImportError: cannot import name 'IS_IPU_AVAILABLE' from 'mmcv.utils'
```

Currently having `mmcv-full==1.7.2, mmdet==2.28.2, mmengine==0.10.4, mmrotate==0.3.4` and `torch=2.2.2+cu121, torchaudio=2.2.2+cu121, torchvision=0.17.2+cu121` on `python=3.9.19` and have a Windows machine with latest CUDA 12.4 installed.

Pls help, much appreciated.

**Comment by xavibou** [comment]
Hi @JoyLinWQ, I am using the following package versions for all my experiments:
- mmcv-full==1.7.2 
- mmdet==2.28.2
- mmrotate==0.3.4
However, the OpenMMLab pacages were used only to test oriented bounding box RPNs, though they are not used in the article as the proposals reliability was low on uncommon, unseen objects. Thus, you should be able to train your prototypes without the OpenMMLab packages, as the experiments use an RPN trained with Detectron2.

Hope this helps

**Comment by JoyLinWQ** [comment]
Hi @xavibou , here's the full traceback:

```
Traceback (most recent call last):
  File "C:\Users\XXX\Documents\ovdsat\train.py", line 6, in <module>
    from models.detector import OVDBoxClassifier, OVDMaskClassifier
  File "C:\Users\XXX\Documents\ovdsat\models\detector.py", line 9, in <module>
    from models.rpn.obb_rpn import OBBRPN
  File "C:\Users\XXX\Documents\ovdsat\models\rpn\obb_rpn.py", line 84, in <module>
    from mmdet.apis import init_detector#, inference_detector
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\mmdet\apis\inference.py", line 10, in <module>
    from mmcv.runner import load_checkpoint
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\mmcv\runner\__init__.py", line 45, in <module>
    from mmcv.device import ipu  # isort:skip  # noqa
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\mmcv\device\__init__.py", line 2, in <module>
    from . import ipu, mlu, mps, npu
  File "C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\mmcv\device\ipu\__init__.py", line 3, in <module>
    from mmcv.utils.device_type import IS_IPU_AVAILABLE
ImportError: cannot import name 'IS_IPU_AVAILABLE' from 'mmcv.utils.device_type' (C:\Users\XXX\anaconda3\envs\ovdsat\lib\site-packages\mmcv\utils\device_type.py)
```

Could u pls help guide how the `modelClass` should be initialised if not using `OVDBoxClassifier` or `OVDMaskClassifier` in `train.py`?

I've downloaded the `weights/rpn_model_final.pth` but unsure where to load it. Pls advise.

```
modelClass = OVDBoxClassifier if args.annotations == 'box' else OVDMaskClassifier
    model = modelClass(all_prototypes, prototypes['label_names'], backbone_type=args.backbone_type, target_size=args.target_size, scale_factor=args.scale_factor).to(device)
    model.train()
```

**Comment by xavibou** [comment]
As you can see on the code, only the classifier is used during training, as it is prototype based, contrary to the RPN, which is pre-trained on a different dataset (e.g. DOTA) with a different set of more common objects. Hence, the RPN weights are not loaded in the training. The RPN weights are only used in the detector class OVDDetector for inference, where the generated proposals will be classified by the trained OVDBoxClassifier. Please refer to the paper for further details: https://arxiv.org/abs/2403.05381.

Your error seems to be related to importing the constant IS_IPU_AVAILABLE from mmcv. This is caused when importing the Detector class because you are trying to use oriented bounding boxes as your RPN, hence when OBBRPN class is imported. The OBBRPN class uses mmdet indeed, though you could start trying by using ordinary bounding boxes, which use detectron2. To resolve the mmcv issue, you could try reinstalling mmcv

pip uninstall mmcv
pip install mmcv

If that does not work, consider installing MMRotate: https://github.com/open-mmlab/mmrotate from zero with the versions mentioned in my earlier response.

In any case, it is strange that this error is thrown during training since the RPN is not used. Where is the ovdsat\models\detector.py being called/imported in the code?

**Comment by JoyLinWQ** [comment]
> Resolving mmcv issue

For this, i've tried the ways u mentioned above too and ran into the import errors above. I have CUDA 12.4 so i cant go below mmcv=2.0.0...

> Where is the ovdsat\models\detector.py being called/imported in the code?

I'm currently trying out your sample data/models by running the training from `bash scripts/train_prototypes_bbox.sh` , specifically from the `train.py` file, after generating the prototypes as outlined in your readme. (manually running the train command just for N=5)

The `ovdsat\models\detector.py` is called inside `train.py -> prepare_model() function` (see function below), due to the use of `OVDBoxClassifier` or `OVDMaskClassifier` when initialising the model. Hence, i was wondering how this can be amended to using ordinary bboxes. Good if u could share another version of `train.py` that uses ordinary bboxes and the `weights/rpn_model_final.pth`.

```
def prepare_model(args):
    # TODO: move to utils or to models __init__.py
    # Use GPU if available
    if torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")
    
    # Load prototypes from checkpoint
    prototypes = torch.load(args.prototypes_path)
    bg_prototypes = torch.load(args.bg_prototypes_path) if args.bg_prototypes_path is not None else None
    if args.bg_prototypes_path is not None:
        all_prototypes = torch.cat([prototypes['prototypes'], bg_prototypes['prototypes']]).float()
    else:
        all_prototypes = prototypes['prototypes']

    # Initialize model and move it to device
    modelClass = OVDBoxClassifier if args.annotations == 'box' else OVDMaskClassifier
    model = modelClass(all_prototypes, prototypes['label_names'], backbone_type=args.backbone_type, target_size=args.target_size, scale_factor=args.scale_factor).to(device)
    model.train()
    
    return model, device
```

**Comment by JoyLinWQ** [comment]
Hi @xavibou , i managed to resolve the OBBRPN error described below, however, when running `train.py` there are issues loading your data as the `train_coco_subset_N5.json` is reading/loading each image (e.g. `ovdsat//data//simd//train//subset_N5\3154.jpg` ), whereas the `ovdsat//data//simd//train//subset_N5` folder contains an additional layer of object categories like airliner, boat, bus, etc. How can this be resolved to load the images for training?

---
Resolving OBBRPN error, in `ovdsat/models/detector.py`:
- Comment out line 9: `from models.rpn.obb_rpn import OBBRPN`
- comment out line 50: `self.rpn = OBBRPN(rpn_config, rpn_checkpoint)` and add some temporary print statement or pass

and in `ovdsat/datasets/dataset.py`:
- Comment out line 12: `rotate_oriented_boxes_batched`

**Comment by xavibou** [comment]
You are right, I just realised I only provided the data subdivided in class directories to initialise the prototypes but it is not suitable for training. Instead, it should start from a unique train directory with all training images, and then:
1 - For prototype initialisation, a 'data/init_data' directory is created with masks for all categories in the subset, which are used to initialise the class-reference prototypes.
2 - The training of these initialised prototypes use the original train directory with all images in one single directory

To fix this, I updated both the source code and the Google Drive data. Download and place the Google Drive directory 'data' inside the repository as shown here:
![Screenshot 2024-05-27 at 14 00 34](https://github.com/xavibou/ovdsat/assets/32686698/95667e61-5b6c-437f-af88-05f3ac7be57a)

Then, when running the init_prototypes, the class-ordered dataset with masks will be automatically created:
![Screenshot 2024-05-27 at 14 02 19](https://github.com/xavibou/ovdsat/assets/32686698/cd1de77f-4538-41a8-8f59-92f5daf8d7a3)

Finally, you should be able to train the initialised prototype from the data/simd/train dataset with the latest push.

Please, let me know if you are able to run the code successfully :)

**Comment by JoyLinWQ** [comment]
@xavibou , thanks, looking great! Yes, i managed to get the training started (before your commit, so `batch_size=8`) by consolidating the unique training images together in a separate folder like you mentioned. 1 epoch was pretty slow...

`init_prototypes` work as intended like you mentioned.

For training, command looks right except these 2 which i think should be:

- `--val_root_dir  ${DATA_DIR}/${dataset}/val` instead of `--val_root_dir  ${DATA_DIR}/${dataset}/train`
- `--val_annotations_file ${DATA_DIR}/${dataset}/val_coco.json` instead of `--val_annotations_file ${DATA_DIR}/${dataset}/train_coco_finetune_val.json`

LMK if the Google drive files for val above should be something else instead.

I'm running into OOM with `batch_size 32`. `batch_size 16` works fine for me (but still really slow - 1 epoch 30mins). Really appreciate your prompt response on this as i'll need to train on other classes too.

After this, for the next step, will need the config files as mentioned in https://github.com/xavibou/ovdsat/issues/2

**Comment by xavibou** [comment]
Great, thanks! Some clarifications with regards to the validation script commands that are the reason for your slow training. This might be a bit confusing and I can change the naming of the variables if necessary, but the train_coco_finetune_val.json and val_coco.json are two different sets here:

- train_coco_finetune_val.json contains a few examples per class extracted from the original train set. The reason for this is to mimic the context of minimal data and we just have a small amount of images to validate. This should be used during training

- val_coco.json is the real validation set of the SIMD dataset, which is used to evaluate after training. This should not be used during training for two reasons: (1) we do not want to expose evaluation examples to the model during training, to be able to obtain a fair evaluation, and (2) the amount of data is much larger and therefore the training is slower.

Remember that we are not optimising weights of a neural network, but rather prototypes, so having a small validation set (or training set) will not have such a big impact in terms of generalisation as if we were training in a traditional Deep Learning manner. In conclusion, you can leave the two training commands --val_root_dir and --val_annotations_file as they were and your training will speed up considerably.

**Comment by JoyLinWQ** [comment]
ah i see, thanks for the explanation, it's much clearer now.

I can't find `train_coco_finetune_val.json` in the Google drive though. Do let me know when its uploaded and i'll get it and re-do the training. We can close this issue then.

**Comment by xavibou** [comment]
Ah, good point! I just added it to the Google Drive directory and should allow you to train. Let me know if you have any other issues and sorry for the confusion!

**Comment by JoyLinWQ** [comment]
thank you @xavibou , all is good now and im starting to get the whole picture. 

one last query regarding the `weights/rpn_model_final.pth`. 
You mentioned in readme that `We pre-trained a FasterRCNN model on DOTA for the RPN using the code from [DroneDetectron2](https://github.com/akhilpm/DroneDetectron2).` 
How and where is this used?

**Comment by xavibou** [comment]
`weights/rpn_model_final.pth` corresponds to the RPN pre-trained weights, which generates bounding boxes where objects might be and the trained classifier classifies them into one of the objects of interest or one of the background prototypes. This is used during inference to detect objects in the OVDDetector class in `models/detector.py`. I do not have the weights with me at the moment but I will try to reproduce them as soon as possible so they are available for the EarthVision workshop at CVPR24. I will treat this on [the other issue ](https://github.com/xavibou/ovdsat/issues/2).

**Comment by Ichini24** [comment]
@xavibou thank you for the work you've done.
I struggle with the launch of described pipeline(creation, tuning prototypes) due to the packages versions. Can you provide requirements.txt with all the packages and versions that are used to launch the project / that are in your launching env, and CUDA version?
