### ISSUE TITLE
Model and config files are misssing in OVDDetector class

### ISSUE THREAD

**Issue by Garvit-32** [xavibou/ovdsat#2]
Hi, While running eval_detection.py, I encountered an error. The pretrained model and config file for the RPN model are missing. Kindly upload it as soon as possible. 

![image](https://github.com/xavibou/ovdsat/assets/54506526/03936a84-8e45-445e-8ab1-dea097519a04)

**Comment by xavibou** [comment]
Hi @Garvit-32, you are right, I will try to add it as soon as possible

**Comment by xavibou** [comment]
@Garvit-32, the config files of the RPN should now be found in the `config/` directory, and the weights of the RPN can be found in the Google Drive directory. Don't forget to add the weights directory in the repository as `ovdsat/weights/`

**Comment by xavibou** [comment]
Pre-trained and initialized prototypes were added to the public Google Drive directory!
