### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by userzhi** [xavibou/ovdsat#5]
hello,  i want to run this repo, but i do not find DIOR data that is annotated with COCO form and used in this repo , where can i get DIOR data

**Comment by AlghaPorthos** [comment]
Hi, I am facing the same issue as you. Do you already find the solution? (such as a format transferer?) @userzhi

**Comment by userzhi** [comment]
i got it by myself, but the result was very terrible

**Comment by userzhi** [comment]
@AlghaPorthos  i have tried to get it by meself, but the result is very terrible

**Comment by xavibou** [comment]
I have created a 'dior' directory in the Google Maps link with the COCO JSON files corresponding to 5-shot, 10-shot, 30-shot and validation sets. Hope this helps.

**Comment by userzhi** [comment]
@xavibou i have got it, thank you
