### ISSUE TITLE
How to use the checkpoints to run object detection tasks?

### ISSUE THREAD

**Issue by AlghaPorthos** [xavibou/ovdsat#6]
Hi, it is really nice to see a project on object detection tasks in RS images. 

I had already finished running the "evaluation" code on my own server, and the outcome is promissing. However, I don't know how to use your checkpoints to run an object detection task on another database? 

Do you have a demostration code on Google Colab (or other project)? Or does this project work with HuggingFace? 

Thank you for your explain!

**Comment by xavibou** [comment]
Hi, there is no notebook example at the moment, but I will keep it in mind to add it in the future. However, you can refer to the `eval_detection.py` for inference and validation of a dataset. I suggest you modify the `init_dataloaders` function in `datasets/__init__.py` according to your needs with your own data.

**Comment by AlghaPorthos** [comment]
> Hi, there is no notebook example at the moment, but I will keep it in mind to add it in the future. However, you can refer to the `eval_detection.py` for inference and validation of a dataset. I suggest you modify the `init_dataloaders` function in `datasets/__init__.py` according to your needs with your own data.

Noted, thank you. Acturally, I modified your codes to do a "simplest test", which is working perfectly on my server. Thank you for your attention, and I am looking forward to your notebook example!

**Comment by xavibou** [comment]
Pre-trained and initialized prototypes were added to the public Google Drive directory!
