### ISSUE TITLE
FSRW available ?

### ISSUE THREAD

**Issue by tcourat** [xavibou/ovdsat#8]
Hi,

Is the experiment using FSRW module available in your repo ?

Thanks

**Comment by xavibou** [comment]
The FSRW experiments are not provided, you can refer to their official repo (https://github.com/DeepTrial/Few-shot-Object-Detection-via-Feature-Reweighting) to train a few-shot method. Then, you just need to use their predictions as bounding box proposals and re-classify them using the prototype-based Classifier module.
